// user
export const SET_USER = 'SET_USER';
export const SET_PHONE = 'SET_PHONE';
export const SET_TOKEN_API = 'SET_TOKEN_API';
export const SET_TOKEN_MEMBER = 'SET_TOKEN_MEMBER';
export const LOCATE_USER = 'LOCATE_USER';
// min
export const INCREMENT_MIN = 'INCREMENT_MIN';
export const DECREMENT_MIN = 'DECREMENT_MIN';
// gym
export const RECEIVE_GYM = 'RECEIVE_GYM';
export const REFRESH_GYM = 'REFRESH_GYM';
export const TOKEN_GYM = 'TOKEN_GYM';
// Buffet
export const RECEIVE_BUFFET = 'RECEIVE_BUFFET';
export const REFRESH_BUFFET = 'REFRESH_BUFFET';
export const TOKEN_BUFFET = 'TOKEN_BUFFET';
// MenuFood & Material in Buffet
export const RECIEVE_MENUFOOD = 'RECIEVE_MENUFOOD';
export const RECIEVE_MATERIAL = 'RECIEVE_MATERIAL';
export const SELECT_BUFFET = 'SELECT_BUFFET';
export const SELECT_GYM = 'SELECT_GYM';
// Store and Products in Store
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const TOKEN_STORE = 'TOKEN_STORE';
export const REFRESH_PRODUCT = 'REFRESH_PRODUCT';
// Blog!
export const RECEIVE_BLOG = 'RECEIVE_BLOG';
export const TOKEN_BLOG = 'TOKEN_BLOG';
export const REFRESH_BLOG = 'REFRESH_BLOG';
export const GET_BUFFET_BASKET = 'GET_BUFFET_BASKET';
export const GET_MATERIAL_BASKET = 'GET_MATERIAL_BASKET';
export const SET_ID_BASKET = 'SET_ID_BASKET';
export const GET_PRODUCT_BASKET = 'GET_PRODUCT_BASKET';
export const SET_ROAD = 'SET_ROAD';
export const SET_ORDER_ID_BUFFET = 'SET_ORDER_ID_BUFFET';
export const SET_ORDER_ID_MATERIAL = 'SET_ORDER_ID_MATERIAL';
export const GET_ORDER_BUFFET = 'GET_ORDER_BUFFET';
export const GET_ORDER_MATERIAL = 'GET_ORDER_MATERIAL';
export const SET_DESC_PRODUCT = 'SET_DESC_PRODUCT';
export const SET_PRODUCT_PRICEALL = 'SET_PRODUCT_PRICEALL';
export const SET_PRODUCT_IDACCESS = 'SET_PRODUCT_IDACCESS';
// HELP !!!
export const HELP_RESET = 'HELP_RESET';
export const HELP_OFF = 'HELP_OFF';
export const HELP_DONE_MEMBER = 'HELP_DONE_MEMBER';
export const HELP_DONE_BUFFET = 'HELP_DONE_BUFFET';
export const HELP_DONE_GYM = 'HELP_DONE_GYM';
export const HELP_DONE_BUFFET_INDEX = 'HELP_DONE_BUFFET_INDEX';
export const HELP_DONE_BUFFET_LIST = 'HELP_DONE_BUFFET_LIST';
export const HELP_DONE_GYM_MAP = 'HELP_DONE_GYM_MAP';
export const HELP_DONE_GYM_LIST = 'HELP_DONE_GYM_MAP';
